use_frameworks!

platform :ios, '10.0'

target 'EmpowerCustomAdapter_Example' do
  pod 'EmpowerCustomAdapter', :path => '../'

  target 'EmpowerCustomAdapter_Tests' do
    inherit! :search_paths

    
  end
end
